"""Report rendering: human-readable Markdown, per-task CSV, JSON export."""

from __future__ import annotations

import csv
import io
import json
from typing import Any

from app.analysis import COMPARISON_METRICS


def _fmt(v: Any) -> str:
    if v is None:
        return "—"
    if isinstance(v, float):
        return f"{v:g}"
    if isinstance(v, bool):
        return "yes" if v else "no"
    return str(v)


def _table(headers: list[str], rows: list[list[Any]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(_fmt(c) for c in row) + " |")
    return "\n".join(lines)


def _cpu_demand(task_cfg: dict[str, Any]) -> int:
    return sum(s.get("d", 0) for s in task_cfg.get("steps", []) if s.get("op") == "cpu")


# ---------------------------------------------------------------------------
# Simulation reports
# ---------------------------------------------------------------------------


def render_report(
    result: dict[str, Any],
    config: dict[str, Any],
    analysis: dict[str, Any] | None = None,
) -> str:
    """Render the full Markdown report for one simulation run."""
    analysis = analysis or {}
    metrics = result.get("metrics", {}) or {}
    scheduler = result.get("scheduler") or {}
    cfg_tasks = {t.get("id"): t for t in config.get("tasks", [])}

    out: list[str] = []
    out.append(f"# Simulation Report — {config.get('name', result.get('configHash'))}")
    out.append("")
    out.append(f"*Generated by MicroRT-Lab analysis layer (config hash "
               f"`{result.get('configHash')}`).*")
    out.append("")

    # -- summary -----------------------------------------------------------
    out.append("## Summary")
    out.append("")
    out.append(
        _table(
            ["Field", "Value"],
            [
                ["Status", result.get("status")],
                ["Scheduler", scheduler.get("type")],
                ["Quantum", scheduler.get("quantum")],
                ["Seed", result.get("seed")],
                ["Duration (ticks)", config.get("duration")],
                ["Simulated until", result.get("simulatedUntil")],
                ["Jobs released / completed", f"{metrics.get('releasedJobs')} / "
                 f"{metrics.get('completedJobs')}"],
                ["Completion rate", metrics.get("completionRate")],
                ["CPU utilization", metrics.get("cpuUtilization")],
                ["Throughput (jobs/tick)", metrics.get("throughput")],
                ["Deadline misses", metrics.get("deadlineMisses")],
                ["Context switches / preemptions", f"{metrics.get('ctxSwitches')} / "
                 f"{metrics.get('preemptions')}"],
            ],
        )
    )
    out.append("")

    # -- workload ----------------------------------------------------------
    out.append("## Workload")
    out.append("")
    out.append(
        _table(
            ["Task", "Kind", "Priority", "Arrival", "Period", "Deadline", "CPU demand", "Steps"],
            [
                [
                    t.get("id"),
                    t.get("kind"),
                    t.get("priority", 0),
                    t.get("arrival", 0),
                    t.get("period"),
                    t.get("relativeDeadline"),
                    _cpu_demand(t),
                    len(t.get("steps", [])),
                ]
                for t in config.get("tasks", [])
            ],
        )
    )
    out.append("")
    if config.get("resources"):
        out.append("Resources: " + ", ".join(
            f"`{r.get('id')}` ({r.get('type')})" for r in config["resources"]))
        out.append("")
    if config.get("memory"):
        mem = config["memory"]
        pool_total = mem.get("blockCount", 0) * mem.get("blockSize", 0)
        out.append(
            f"Memory model: {mem.get('model')}, policy {mem.get('policy')}, "
            f"total {mem.get('total', pool_total)} bytes"
        )
        out.append("")
    if config.get("aging"):
        out.append(
            f"Aging: interval {config['aging'].get('interval')}, "
            f"cap {config['aging'].get('cap')}"
        )
        out.append("")

    # -- per-task metrics ---------------------------------------------------
    out.append("## Per-task metrics")
    out.append("")
    rows = []
    for t in result.get("tasks", []) or []:
        waits = t.get("waitTimes") or []
        turns = t.get("turnaroundTimes") or []
        rows.append(
            [
                t.get("id"),
                t.get("jobsReleased"),
                t.get("jobsCompleted"),
                t.get("deadlineMisses"),
                t.get("cpuTime"),
                t.get("readyWaitTotal"),
                t.get("blockedTotal"),
                t.get("firstStart"),
                t.get("lastFinish"),
                round(sum(waits) / len(waits), 3) if waits else None,
                round(sum(turns) / len(turns), 3) if turns else None,
                "STARVED" if t.get("starved") else "",
            ]
        )
    out.append(
        _table(
            ["Task", "Released", "Completed", "Misses", "CPU", "ReadyWait",
             "Blocked", "First", "Last", "Avg wait", "Avg turn", "Starved"],
            rows,
        )
    )
    out.append("")

    # -- engine vs recomputed ------------------------------------------------
    recompute = analysis.get("recompute")
    if recompute:
        out.append("## Metrics cross-check (engine vs Python recomputation)")
        out.append("")
        eng = recompute.get("engine") or {}
        rec = recompute.get("recomputed") or {}
        deltas = recompute.get("deltas") or {}
        out.append(
            _table(
                ["Metric", "Engine", "Recomputed", "Delta"],
                [
                    [k, eng.get(k), rec.get(k), deltas.get(k)]
                    for k in ("avgWaiting", "avgTurnaround", "avgResponse",
                              "cpuUtilization", "throughput")
                ],
            )
        )
        out.append("")
        out.append(f"Match within tolerance {recompute.get('tolerance')}: "
                   f"**{'yes' if recompute.get('match') else 'NO'}**")
        out.append("")

    # -- anomalies ------------------------------------------------------------
    anomalies = result.get("anomalies") or []
    out.append(f"## Anomalies ({len(anomalies)})")
    out.append("")
    if anomalies:
        out.append(
            _table(
                ["t", "type", "tasks", "resources", "detail"],
                [
                    [a.get("t"), a.get("type"), ", ".join(a.get("tasks") or []),
                     ", ".join(a.get("resources") or []), a.get("detail")]
                    for a in anomalies
                ],
            )
        )
    else:
        out.append("None.")
    out.append("")

    # -- deadline misses --------------------------------------------------------
    miss_rows = [
        [t.get("id"), t.get("deadlineMisses"), t.get("jobsReleased")]
        for t in result.get("tasks", []) or [] if (t.get("deadlineMisses") or 0) > 0
    ]
    out.append("## Deadline misses")
    out.append("")
    if miss_rows:
        out.append(_table(["Task", "Misses", "Released"], miss_rows))
    else:
        out.append("None — every completed job met its deadline.")
    out.append("")

    # -- deadlocks ---------------------------------------------------------------
    deadlocks = result.get("deadlocks") or []
    out.append(f"## Deadlocks ({len(deadlocks)})")
    out.append("")
    if deadlocks:
        out.append(
            _table(
                ["t", "cycle", "tasks", "resources"],
                [
                    [d.get("t"), " → ".join(d.get("cycle") or []),
                     ", ".join(d.get("tasks") or []),
                     ", ".join(d.get("resources") or [])]
                    for d in deadlocks
                ],
            )
        )
    else:
        out.append("None.")
    out.append("")

    # -- memory / fragmentation -----------------------------------------------------
    frag = analysis.get("fragmentation") or {}
    if frag.get("enabled"):
        out.append("## Memory & fragmentation")
        out.append("")
        out.append(
            _table(
                ["Field", "Value"],
                [
                    ["Model / policy", f"{frag.get('model')} / {frag.get('policy')}"],
                    ["Peak usage (bytes)", frag.get("peakUsage")],
                    ["Alloc failures", frag.get("allocFailures")],
                    ["Leaks", frag.get("leakCount")],
                    ["Fragmentation avg / max", f"{frag.get('fragmentationAvg')} / "
                     f"{frag.get('fragmentationMax')}"],
                    ["Final free (free / largest / frag)",
                     f"{frag['finalFree']['free']} / {frag['finalFree']['largest']} / "
                     f"{frag['finalFree']['fragmentation']}"],
                ],
            )
        )
        out.append("")

    # -- starvation ---------------------------------------------------------------------
    starve = analysis.get("starvation")
    if starve:
        out.append(f"## Starvation (threshold {starve.get('threshold')} ticks)")
        out.append("")
        if starve.get("starvedCount"):
            for entry in starve["starvedTasks"]:
                out.append(
                    f"- **{entry['id']}** starved: readyWait {entry['readyWaitTotal']} "
                    f"ticks vs cpuTime {entry['cpuTime']} "
                    f"(jobs {entry['jobsCompleted']}/{entry['jobsReleased']} completed)"
                )
        else:
            out.append("No starved tasks.")
        out.append("")

    # -- real-time analysis ------------------------------------------------------------------
    rt = analysis.get("rt")
    if rt:
        theory = rt.get("theoretical") or {}
        meas = rt.get("measured") or {}
        out.append("## Real-time analysis")
        out.append("")
        out.append("### Theoretical (from authored parameters)")
        out.append("")
        out.append(
            _table(
                ["Task", "WCET", "Period", "Deadline", "Utilization"],
                [
                    [t.get("id"), t.get("wcet"), t.get("period"),
                     t.get("relativeDeadline"), t.get("utilization")]
                    for t in theory.get("tasks") or []
                ],
            )
        )
        out.append("")
        hyp = theory.get("hyperbolicBound") or {}
        out.append(
            f"- Total utilization U = **{theory.get('totalUtilization')}** on "
            f"{theory.get('periodicTaskCount')} periodic tasks"
        )
        verdict = "below (sufficient)" if theory.get("liuLaylandSchedulable") else (
            "above (inconclusive)"
        )
        out.append(
            f"- Liu & Layland bound n(2^(1/n)-1) = **{theory.get('liuLaylandBound')}** "
            f"→ {verdict}"
        )
        if hyp:
            out.append(
                f"- Hyperbolic bound Π(Uᵢ+1) = **{hyp.get('product')}** ≤ 2 → "
                f"{'schedulable' if hyp.get('schedulable') else 'not guaranteed'}"
            )
        out.append("")
        out.append("### Measured (from the simulation)")
        out.append("")
        out.append(
            _table(
                ["Task", "Released", "Completed", "Misses", "CPU", "Starved"],
                [
                    [t.get("id"), t.get("jobsReleased"), t.get("jobsCompleted"),
                     t.get("deadlineMisses"), t.get("cpuTime"),
                     "yes" if t.get("starved") else ""]
                    for t in meas.get("perTask") or []
                ],
            )
        )
        out.append("")
        out.append(f"Verdict: {rt.get('verdict')}")
        out.append("")

    # -- per-config notes --------------------------------------------------------------
    unused = [tid for tid in cfg_tasks if tid not in
              {t.get("id") for t in result.get("tasks", [])}]
    if unused:  # pragma: no cover - defensive
        out.append(f"Tasks without accounting: {', '.join(unused)}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_task_csv(result: dict[str, Any]) -> str:
    """Per-task metrics as CSV."""
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(
        [
            "taskId", "jobsReleased", "jobsCompleted", "deadlineMisses", "cpuTime",
            "readyWaitTotal", "blockedTotal", "waitingTotal", "sleepingTotal",
            "firstStart", "lastFinish", "avgWait", "avgTurnaround", "avgResponse",
            "starved",
        ]
    )
    for t in result.get("tasks", []) or []:
        waits = t.get("waitTimes") or []
        turns = t.get("turnaroundTimes") or []
        resps = t.get("responseTimes") or []
        writer.writerow(
            [
                t.get("id"), t.get("jobsReleased"), t.get("jobsCompleted"),
                t.get("deadlineMisses"), t.get("cpuTime"), t.get("readyWaitTotal"),
                t.get("blockedTotal"), t.get("waitingTotal"), t.get("sleepingTotal"),
                t.get("firstStart"), t.get("lastFinish"),
                round(sum(waits) / len(waits), 3) if waits else "",
                round(sum(turns) / len(turns), 3) if turns else "",
                round(sum(resps) / len(resps), 3) if resps else "",
                1 if t.get("starved") else 0,
            ]
        )
    return buf.getvalue()


def render_json_export(
    result: dict[str, Any], config: dict[str, Any], analysis: dict[str, Any] | None = None
) -> str:
    """Full JSON export: config + result + analysis bundle."""
    return json.dumps(
        {
            "config": config,
            "result": result,
            "analysis": analysis or {},
        },
        indent=2,
        separators=(",", ": "),
    )


# ---------------------------------------------------------------------------
# Comparison reports
# ---------------------------------------------------------------------------


def render_comparison_report(comparison: dict[str, Any]) -> str:
    """Markdown report for a stored comparison (variants × metrics + verdicts)."""
    base = comparison.get("baseConfig") or {}
    results = comparison.get("results") or {}
    variants = results.get("variants") or []
    out: list[str] = []
    out.append(f"# Comparison Report — {comparison.get('name') or comparison.get('id')}")
    out.append("")
    out.append(
        f"Base experiment: **{base.get('name')}** "
        f"(scheduler `{(base.get('scheduler') or {}).get('type')}`, "
        f"{len(base.get('tasks', []))} tasks, duration {base.get('duration')})."
    )
    out.append("")
    out.append("Variant overrides are deep-merged over the base config "
               "(dicts merge recursively, lists are replaced).")
    out.append("")

    metric_keys = list(COMPARISON_METRICS)
    header = ["Metric"] + [v.get("label", "?") for v in variants]
    rows: list[list[Any]] = []
    for key in metric_keys:
        rows.append([key] + [(v.get("metrics") or {}).get(key) for v in variants])
    out.append("## Per-variant metrics")
    out.append("")
    out.append(_table(header, rows))
    out.append("")

    best = results.get("bestPerMetric") or {}
    if best:
        out.append("## Best per metric")
        out.append("")
        out.append(
            _table(
                ["Metric", "Best variant", "Value", "Direction"],
                [
                    [key, entry.get("label"), entry.get("value"),
                     COMPARISON_METRICS.get(key)]
                    for key, entry in best.items()
                ],
            )
        )
        out.append("")

    deltas = results.get("deltasVsFirst") or []
    if deltas:
        out.append("## Delta vs first variant (baseline)")
        out.append("")
        out.append(
            _table(
                ["Variant"] + metric_keys,
                [[d.get("label")] + [d.get("metrics", {}).get(k) for k in metric_keys]
                 for d in deltas],
            )
        )
        out.append("")

    starved = [v for v in variants if (v.get("starvedTaskIds") or [])]
    if starved:
        out.append("## Starvation per variant")
        out.append("")
        for v in starved:
            out.append(f"- **{v.get('label')}**: starved — "
                       f"{', '.join(v['starvedTaskIds'])}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


__all__ = [
    "render_comparison_report",
    "render_json_export",
    "render_report",
    "render_task_csv",
]
